// Action Types
export const TICKETS_ACTION_TYPES = {
  // Loading states
  SET_LOADING: 'TICKETS_SET_LOADING',
  SET_REFRESHING: 'TICKETS_SET_REFRESHING',
  
  // Tickets data
  SET_TICKETS: 'TICKETS_SET_TICKETS',
  ADD_TICKET: 'TICKETS_ADD_TICKET',
  UPDATE_TICKET: 'TICKETS_UPDATE_TICKET',
  DELETE_TICKET: 'TICKETS_DELETE_TICKET',
  
  // Dashboard stats
  SET_STATS: 'TICKETS_SET_STATS',
  
  // Filters and pagination
  SET_FILTERS: 'TICKETS_SET_FILTERS',
  SET_PAGINATION: 'TICKETS_SET_PAGINATION',
  SET_SELECTED: 'TICKETS_SET_SELECTED',
  
  // Closed and Archived tickets
  SET_CLOSED_TICKETS: 'TICKETS_SET_CLOSED_TICKETS',
  SET_ARCHIVED_TICKETS: 'TICKETS_SET_ARCHIVED_TICKETS',
  
  // Metadata
  SET_AGENTS: 'TICKETS_SET_AGENTS',
  SET_GROUPS: 'TICKETS_SET_GROUPS',
  SET_PRIORITIES: 'TICKETS_SET_PRIORITIES',
  SET_TYPES: 'TICKETS_SET_TYPES',
  
  // Error handling
  SET_ERROR: 'TICKETS_SET_ERROR',
  CLEAR_ERROR: 'TICKETS_CLEAR_ERROR',
  
  // Real-time updates
  TICKET_UPDATED: 'TICKETS_TICKET_UPDATED',
  TICKET_STATUS_CHANGED: 'TICKETS_TICKET_STATUS_CHANGED'
};